pinggame:
  image: ubuntu:16.04
  before_script:
    - apt-get update
    - apt-get install apache2
    - apt-get install php5 libapache2-mod-php5 php5-mcrypt
    - a2enmod rewrite
  script:
    - php -S localhost:8080
